version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_test1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rona
      MYSQL_DATABASE: test1db
    ports:
      - "9000:3306"
    volumes:
      - mysql_test1:/var/lib/mysql
    networks:
      - weblab700
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_700
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rona
      UPLOAD_LIMIT: 64M 
    ports:
      - "8701:80"
    depends_on:
      - db
    networks:
      - weblab700
    restart: always

networks:
  weblab700:
    driver: bridge

volumes:
  mysql_test1:
    driver: local